In [11]:
import os
import matplotlib.pyplot as plt
import joblib
import pandas as pd
import numpy as np

plt.style.use("fivethirtyeight")

In [29]:
class perceptron:
    def __init__(self, eta: float=None, epochs: int=None):
        self.weights = np.random.randn(3) * 1e-4
        self.eta = eta #learning rate
        self.epochs = epochs #iterations
        
    def _z_outcome(self, inputs, weights): # starting point , inputs*weights
        return np.dot(inputs,weights)
        
    def activation_function(self,z):
        return np.where(z> 0, 1, 0) #z>0 output will be one
    
    def fit(self, X, y):
        self.X = X
        self.y = y
        
        X_with_bias = np.c_[self.X, -np.ones((len(self.X),1))]
        print(f"X with bias:\n{X_with_bias}")
        
        for epoch in range(self.epochs):
            print("----"*10)
            print(f"for epoch >> {epoch+1}")
            print("----"*10)
            
            z = self._z_outcome(X_with_bias, self.weights)
            y_hat = self.activation_function(z)
            print(f"predicted value after the forward pass:\n{y_hat}")
            
            self.error = self.y - y_hat
            print(f"error:\n{self.error}")
            self.weights = self.weights + self.eta * np.dot(X_with_bias.T, self.error)
            print(f"updated weights after epoch: {epoch+1}/{self.epochs}: \n{y_hat}")
            print(f"##"*10)

    def predict(self, X):
        X_with_bias = np.c_[X, -np.ones((len(X),1))]
        z = self._z_outcome(X_with_bias, self.weights)
        return self.activation_function(z)

In [30]:
OR = {
    "x1" : [0,0,1,1],
    "x2" : [0,1,0,1],
    "y"  : [0,1,1,1]
}

df_OR = pd.DataFrame(OR)

df_OR

x1  x2  y
0   0   0  0
1   0   1  1
2   1   0  1
3   1   1  1

In [31]:
def prepare_data(df, target_col="y"):
    X = df.drop(target_col, axis = 1)
    y = df[target_col]
    return X,y

In [36]:
X, y = prepare_data(df_OR)

ETA = 0.1
EPOCHS = 10

model_or = perceptron(eta = ETA, epochs = EPOCHS)

model_or.fit(X, y)

X with bias:
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
----------------------------------------
for epoch >> 1
----------------------------------------
predicted value after the forward pass:
[1 1 1 1]
error:
0   -1
1    0
2    0
3    0
Name: y, dtype: int64
updated weights after epoch: 1/10: 
[1 1 1 1]
####################
----------------------------------------
for epoch >> 2
----------------------------------------
predicted value after the forward pass:
[0 0 0 0]
error:
0    0
1    1
2    1
3    1
Name: y, dtype: int64
updated weights after epoch: 2/10: 
[0 0 0 0]
####################
----------------------------------------
for epoch >> 3
----------------------------------------
predicted value after the forward pass:
[1 1 1 1]
error:
0   -1
1    0
2    0
3    0
Name: y, dtype: int64
updated weights after epoch: 3/10: 
[1 1 1 1]
####################
----------------------------------------
for epoch >> 4
----------------------------------------
predicted value 

In [15]:
X

x1  x2
0   0   0
1   0   1
2   1   0
3   1   1

In [16]:
y

0    0
1    1
2    1
3    1
Name: y, dtype: int64

In [28]:
model_or.predict(X)

array([0, 1, 1, 1])

In [34]:
np.random.randn(3) * 1e-4

array([ 2.11071552e-06, -8.92504753e-05,  1.26404910e-04])